name: julian_medical_center
description: A responsive web and mobile frontend for Julian Medical Center.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  lucide_icons: ^0.257.0
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  # Add these two lines exactly:
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # --- ADD THESE THREE LINES ---
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
